# Generated by Django 3.0.3 on 2020-02-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailforsend',
            name='is_send',
            field=models.BooleanField(),
        ),
    ]
